# Generated by Django 4.2.1 on 2023-05-16 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=32, null=True, verbose_name='id')),
                ('name', models.CharField(blank=True, max_length=32, null=True, verbose_name='name')),
                ('tel', models.CharField(blank=True, max_length=32, null=True, verbose_name='연락처')),
            ],
            options={
                'verbose_name': '회원',
                'verbose_name_plural': '회원',
                'db_table': 'user_info',
            },
        ),
    ]
